const constants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE', 
    LOGOUT: 'USERS_LOGOUT',
    TOGGLE_MENU: 'TOGGLE_MENU',
    TOGGLE_FILTER: 'TOGGLE_FILTER',
    SWITCH_LOGIN: 'SWITCH_LOGIN',
    SWITCH_REGISTER: 'SWITCH_REGISTER'
};

export default constants;